name: zezis_functions
description: Functions in a customized way and with easy dependency management.

version: 0.0.15
repository: https://github.com/joseaugustoaquino/zezis_functions
homepage: https://github.com/joseaugustoaquino

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
    
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
    